spring.application.name=Computadoras
server.port=8001

#Conexion a la bd
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1

#Credenciales
spring.datasource.username=DAVID
spring.datasource.password=enucom

#Driver Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#JPA
spring.jpa.database=oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

#Mostrar SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true